### ISSUE TITLE
ViewExtension should use CommandExecutive API instead of ViewModel access.

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/TuneUp#1]
exposed here
https://github.com/DynamoDS/Dynamo/blob/35e31271ec1e75fb547352a347c2f002c7df5a89/src/DynamoCoreWpf/Extensions/ViewLoadedParams.cs#L127

see here for implementation
https://github.com/DynamoDS/Dynamo/blob/8afcde02f859f5dd4f261d21edb32e2b94e9450a/src/DynamoCoreWpf/Extensions/ViewExtensionCommandExecutive.cs

- [x] use this to run commands like FitView etc.
- [x] don't zoom fully into the node when user clicks the entry in the table.
- [x] Attempt to reduce all use of access to ViewModel by getting dataContext.

**Comment by scottmitchell** [comment]
@mjkkirschner Do you know if `ZoomToSelected` or similar functionality currently exists as part of this API? I've been checking out the `CommandExecutive` and `RecordableCommands` but haven't seen a command for this. Was your idea with this task that I would also implement necessary commands on the Dynamo side?

**Comment by mjkkirschner** [comment]
the command is here:
https://github.com/DynamoDS/Dynamo/blob/ec10f936824152e7dd7d6d019efdcda0d78a5264/src/DynamoCoreWpf/ViewModels/Core/DynamoViewModelDelegateCommands.cs#L40

it has a terrible name. 😢

**Comment by mjkkirschner** [comment]
@scottmitchell whoops:
https://github.com/DynamoDS/Dynamo/blob/ec10f936824152e7dd7d6d019efdcda0d78a5264/src/DynamoCoreWpf/ViewModels/Core/DynamoViewModelDelegateCommands.cs#L74

slightly better name - this zooms the selection as long as the graph is active (background preview not active)

**Comment by scottmitchell** [comment]
@mjkkirschner I could totally be misunderstanding this, but it looks like the command executive can only execute commands that are implemented as `RecordableCommands`. If that's true, the currently available recordable commands get me halfway there. I can [select](https://github.com/DynamoDS/TuneUp/pull/14/files#diff-e12004fd73937f5ec59b978666363cfcR47-R48) using the `CommandExecutive`, but I have to use the `ViewModel` to [zoom](https://github.com/DynamoDS/TuneUp/pull/14/files#diff-e12004fd73937f5ec59b978666363cfcR51) using the `FitViewCommand`, which is not a `RecordableCommand`.

**Comment by mjkkirschner** [comment]
I think we need to do two things - add a new interface - iviewmodelcommandExecutive which adds another public method for executing delegate commands - adding this to the api without breaking compatibility will likely be ugly but is totally worth it. By that I mean requires obsoleting the existing command executive property on viewLoadedParams
