### ISSUE TITLE
User should be able to force Re-execute the graph from within TuneUp

### ISSUE THREAD

**Issue by scottmitchell** [DynamoDS/TuneUp#2]
- [ ] Add a "Recompute" button that forces re-execution of the graph
- [ ] Reset profiling for all nodes on "Recompute"

**Comment by scottmitchell** [comment]
- [ ] Add a "Recompute" button that forces re-execution of the graph
- [ ] Reset profiling for all nodes on "Recompute"

**Comment by QilongTang** [comment]
I think we already have this, closing
