### ISSUE TITLE
TuneUp compatibility with Dynamo 3.xx

### ISSUE THREAD

**Issue by VivienMollard** [DynamoDS/TuneUp#42]
Hi,
I'm wondering if TuneUp will be updated for Dynamo 3.xx
I'm currently working with Dynamo v.3.0.3, but after TuneUp installation, it don't see it in "View" anymore, so I suspect that it's not compatible with this Dynamo version.
I love so much the Force Re-Execute functionality that I would really love to be able to use it in the future.
Thanks in advance for your reply!

**Comment by QilongTang** [comment]
Hi @VivienMollard Yes, the work is in progress, see work in progress pull request as https://github.com/DynamoDS/TuneUp/pull/41. Once we finished the .NET8 migration, we will republish and additional improvements are baking as well

**Comment by VivienMollard** [comment]
Hi @QilongTang!
Thank you very much for the follow up. Keep up the good work! Have a good day.

**Comment by QilongTang** [comment]
@VivienMollard My pleasure

**Comment by Amoursol** [comment]
@VivienMollard the TuneUp package has been updated now and is accessible on the Package Manager. Version 1.0.8 and above will work correctly with Dynamo 3.0 and above.
